### ISSUE TITLE
Cpu Strange Behavior 

### ISSUE THREAD

**Issue by Chemicals-that-make-the-frogs-gay** [inoueaus/euchre_on_rails#15]
This also isn't too big of a deal, but if a player has the ability to lead off a trick, and they have the right bower (jack of trump suit) they will ALWAYS play the right bower. The CPUs rarely ever do this and lose trucks that they should have won.

**Comment by Chemicals-that-make-the-frogs-gay** [comment]
Also, if the right bower is laid, the default behavior should ve to play your lowest trump card. I have seen CPUs play the left bower only to inevitably lose that trick,  then go on to play a 9 or 10 in trump

**Comment by inoueaus** [comment]
Changed the logic to that cards of high value will be placed at top of list for cpus to use when they do not have to follow suit. Also they now use their worst cards when they cannot follow suit or trump.
