### ISSUE TITLE
Limit The Score to 10

### ISSUE THREAD

**Issue by Chemicals-that-make-the-frogs-gay** [inoueaus/euchre_on_rails#18]
10 is the maximum score, but if you have 9 and win all 5 tricks, euchre your opponent,  or get a loner you will end up with more than 10 points
![Screenshot_20210828-100407_Chrome](https://user-images.githubusercontent.com/89693147/131220532-514f09da-e525-4dc2-87b5-521263e3d258.jpg)

**Comment by inoueaus** [comment]
Fixed by adding rand(0..3) to initialize in round. 
<img width="894" alt="スクリーンショット 2021-08-29 7 42 29" src="https://user-images.githubusercontent.com/87982396/131232756-54979d84-e7a7-4815-bdc0-64637fe9c376.png">
